---
Name: prefixrequirements
After: coreresources
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Core\Manifest\ResourceURLGenerator:
    class: Innoweb\PrefixRequirements\Control\PrefixResourceURLGenerator
    properties:
      nonceStyle: mtime
